FROM maven:latest AS build

WORKDIR /app
COPY ./pom.xml ./pom.xml
COPY ./src ./src

RUN mvn clean compile assembly:single

FROM openjdk:21
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar

# Define the default command to run when the container starts
CMD ["java", "-jar", "/app/app.jar"]

# Set the command-line argument as an environment variable
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
