FROM maven:latest AS build

WORKDIR /app
COPY docker/image-auditor/pom.xml ./pom.xml
COPY docker/image-auditor/src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar

# Define the default command to run when the container starts
CMD ["java", "-jar", "/app/app.jar"]

